### ISSUE TITLE
Model training freezed

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/YOLO-Nano#4]
Model is just freezed at this line. Training flow doesn't enter this for loop. Is there any particular reason for this behavior?

https://github.com/yjh0410/YOLO-Nano/blob/018f61ce1fb3511420fef78afe947bdb8182b54b/train.py#L187

Thanks in advanace

**Comment by yjh0410** [comment]
@kulkarnikeerti  Sorry, I can't understand your question about "Model is just freezed at this line. Training flow doesn't enter this for loop". Are there any bugs or errors reported ?

**Comment by kulkarnikeerti** [comment]
Hi, there is no error that is reported, it just stops before the loop. Below you can find the snapshot of the same.

![image](https://user-images.githubusercontent.com/12002873/158122898-6393ebb7-32d0-4052-81db-527262aad6fd.png)

I have added the  `before images and targets` `print` statement just before the `for` loop. As you can see the execution flow just stops right there. I don't see any errors or any information. 

@yjh0410 Do you know what might be the issue at this point?
Thanks.

**Comment by kulkarnikeerti** [comment]
I think the reason for this freeze might be that the dataloader is empty. Do you also think the same? Can you please let me know why the dataloader is not working properly? @yjh0410 Could you please confirm from your side that its working without any issues.

**Comment by yjh0410** [comment]
@kulkarnikeerti 
I haven't debugged this project for a long time. You can use my other YOLO project, which also has YOLO-Nano.

https://github.com/yjh0410/PyTorch_YOLO-Family

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thanks
